### ISSUE TITLE
CV.search.DPDU.regression error

### ISSUE THREAD

**Issue by Dom-Owens-UoB** [HaotianXu/changepoints#1]
Using `CV.search.DPDU.regression` occasionally returns the error

> Error in lassoDPDU_error(train.y[(init_train_cpt_long[i] + 1):init_train_cpt_long[i +  : 
  Not a matrix.

I assume the issue is with the argument inputs, this could maybe be resolved just by wrapping them in `as.matrix`?

This can be replicated with the following code

`DPDU_null <- function(max_iter=100 ){ 
  scale <- 10
  n <- 300
  p <- 100
  Sigma <- stats::toeplitz( .6^(1:p - 1)) * scale^2
  cps <- c(100,200)
  
  out_q <- matrix(0, max_iter, 3)
  b_3 <- c( rep(c(1,-1), 5), rep(0, p-10))
  
  kappa <- c(1,1.2,1.4,1.6) * sqrt(40) 
  out_q <- matrix(0, max_iter, 4) 
  for (iter in 1:max_iter) {
    #if(iter%%10 == 1) 
      print(iter)
    set.seed(iter)
    X_1 <- mvrnorm(n, rep(0,p), Sigma) 
    y_1 <- X_1[1:100,] %*% b_3 #+ rnorm(100)
    y_2 <- X_1[101:200,] %*% b_3 #+ rnorm(100)
    y_3 <- X_1[201:300,] %*% b_3 #+ rnorm(100)
    
    for (ka in 1:length(kappa)) {
      y_1ka <- y_1 * kappa[ka]/sqrt(40) + rnorm(100)* scale
      y_2ka <- y_2 * kappa[ka]/sqrt(40) + rnorm(100)* scale
      y_3ka <- y_3 * kappa[ka]/sqrt(40) + rnorm(100)* scale
      y <- c(y_1ka,y_2ka,y_3ka) 
      
      
      lambda_set =  c(0.3, 0.5, 1, 2)# c(0.01, 0.1, 1, 2)
      zeta_set = c(10, 15, 20)
      temp = CV.search.DPDU.regression(y = y, X = X_1, lambda_set, zeta_set)
      #temp$test_error # test error result
      # find the indices of lambda_set and zeta_set which minimizes the test error
      min_idx = as.vector(arrayInd(which.min(temp$test_error), dim(temp$test_error)))
      #lambda_set[min_idx[2]]
      #zeta_set[min_idx[1]]
      cpt_init = unlist(temp$cpt_hat[min_idx[1], min_idx[2]])
      q <- length(cpt_init)
      out_q[iter,ka] <- q
    }
    
  }
  return(out_q)
}
DPDU_null_res <- DPDU_null(100) `

**Comment by HaotianXu** [comment]
The error occurred due to improper matrix multiplication formatting. I have corrected this bug. Thank you so much for pointing this error!
